import './globals.css'
import CustomCursor from '@/components/ui/CustomCursor'
import GlobalAIChatWidget from '@/components/ui/GlobalAIChatWidget'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CustomCursor />
        {children}
        <GlobalAIChatWidget />
      </body>
    </html>
  )
}
